openapi: 3.0.3
info:
  title: OpenApi RouteExpander
  description: API for Test.
  version: 0.0.1
servers:
  - url: https://{host}
    variables:
      host:
        default: ""
        description: Server URL
paths:
  /:
    $ref: "./routes.yaml#/paths"
components:
  schemas:
    Schema1:
      $ref: "./schemas.yaml#/components/schemas/Schema1"
    Schema2:
      $ref: "./schemas.yaml#/components/schemas/Schema2"
