name: Release
run-name: "Release"
on:
  workflow_dispatch:
    inputs:
      increment-type:
        description: 'Version increment type (patch, minor, major)'
        required: true
        default: 'patch'
        type: 'choice'
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.pat_github}}
        ref: main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
    - name: Update package
      id: update_package
      run: |
        git config --global user.email "yog27ray@example.com"
        git config --global user.name "Yogendra Singh"
        VERSION=$(npm version ${{ github.event.inputs.increment-type }})
        npm run build
        cd dist
        ls -lah
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
